package placement_scheduler.service;
 
import java.time.LocalTime;
 
/**
 * Immutable value holder for a candidate interview slot: a specific day
 * plus a start/end time. Generated by SchedulingService#generateTimeSlots
 * and never persisted directly — once a slot is chosen, its day/start/end
 * are copied onto the actual Interview entity.
 */
public class TimeSlot {
 
    private final int day;
    private final LocalTime startTime;
    private final LocalTime endTime;
 
    public TimeSlot(int day, LocalTime startTime, LocalTime endTime) {
        this.day = day;
        this.startTime = startTime;
        this.endTime = endTime;
    }
 
    public int getDay() {
        return day;
    }
 
    public LocalTime getStartTime() {
        return startTime;
    }
 
    public LocalTime getEndTime() {
        return endTime;
    }
}
